import {test, expect} from '@playwright/test'

test.beforeEach(async ({ page }) => {
     await page.goto('https://katalon-demo-cura.herokuapp.com/')
    await page.locator("#btn-make-appointment").click()
    await page.locator("#txt-username").fill("John Doe")
    await page.locator("#txt-password").fill("ThisIsNotAPassword")
    await page.locator("#btn-login").click()
    await expect(page.locator("text=Make Appointment")).toBeVisible()
})


test('Make appointment with healthcare program Medicare', async({page})=>{
    await page.locator("#combo_facility").selectOption("Hongkong CURA Healthcare Center")
    await page.locator("#chk_hospotal_readmission").check()
    await page.locator("#radio_program_medicare").check()
    await page.locator("#txt_visit_date").click()
    await page.locator(".datepicker-days >> text=15").click()
    await page.locator("#txt_comment").fill("This is a comment")
    await page.locator("#btn-book-appointment").click()
    await expect(page.locator("text=Appointment Confirmation")).toBeVisible()
    await expect(page.locator("#facility")).toHaveText("Hongkong CURA Healthcare Center")
    await expect(page.locator("#hospital_readmission")).toHaveText("Yes")
    await expect(page.locator("#program")).toHaveText("Medicare")
    await expect(page.locator("#visit_date")).toHaveText(/15.*/)
    await expect(page.locator("#comment")).toHaveText("This is a comment")   
})

test('Make appointment with healthcare program Medicaid', async({page})=>{
    await page.locator("#combo_facility").selectOption("Hongkong CURA Healthcare Center")
    await page.locator("#chk_hospotal_readmission").check()
    await page.locator("#radio_program_medicaid").check()
    await page.locator("#txt_visit_date").click()
    await page.locator(".datepicker-days >> text=15").click()
    await page.locator("#txt_comment").fill("This is a comment")
    await page.locator("#btn-book-appointment").click()
    await expect(page.locator("text=Appointment Confirmation")).toBeVisible()
    await expect(page.locator("#facility")).toHaveText("Hongkong CURA Healthcare Center")
    await expect(page.locator("#hospital_readmission")).toHaveText("Yes")
    await expect(page.locator("#program")).toHaveText("Medicaid")
    await expect(page.locator("#visit_date")).toHaveText(/15.*/)
    await expect(page.locator("#comment")).toHaveText("This is a comment")
})

test('Make appointment with no healthcare program', async({page})=>{
    await page.locator("#combo_facility").selectOption("Hongkong CURA Healthcare Center")
    await page.locator("#chk_hospotal_readmission").check()
    await page.locator("#radio_program_none").check()
    await page.locator("#txt_visit_date").click()
    await page.locator(".datepicker-days >> text=15").click()
    await page.locator("#txt_comment").fill("This is a comment")
    await page.locator("#btn-book-appointment").click()
    await expect(page.locator("text=Appointment Confirmation")).toBeVisible()
    await expect(page.locator("#facility")).toHaveText("Hongkong CURA Healthcare Center")
    await expect(page.locator("#hospital_readmission")).toHaveText("Yes")
    await expect(page.locator("#program")).toHaveText("None")
    await expect(page.locator("#visit_date")).toHaveText(/15.*/)
    await expect(page.locator("#comment")).toHaveText("This is a comment")
})